<meta charset="UTF-8">
<title>Thenet.ca :: COMP1950 SITE</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<script src="assets/javascript/scrollTo.js"></script>
<script src="assets/javascript/script.js"></script>
<link rel="stylesheet" href="assets/fonts/webfontkit-20140127-152607/stylesheet.css">
<link rel="stylesheet" href="assets/css/normalize.css">
<link rel="stylesheet" href="assets/css/foundation.min.css">
<link rel="stylesheet" href="assets/css/style.css">