<header id="main">
  <div class="row">
    <div class="columns large-8">
      <a href="/tbd/proto_site"><h1>BCIT COMP 1950 <small>Intermediate Web Design & Development</small></h1></a>
    </div>
    <div class="columns large-4">
      <form>
        <div class="large-8 right">
          <div class="row">
            <div class="large-10 columns">
              <div class="row collapse">
                <div class="columns large-11">
                  <input type="text" id="right-label" placeholder="Search">
                </div>
                <div class="columns large-1">
                  <button class="postfix inline">S</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</header>
