<nav id="main">
          <h3>LECTURES</h3>
          <ul>
            <li><a href="week1.shtml">01 | Introduction</a></li>
            <li><a href="week2.shtml">02 | tools & standards</a></li>
            <li>03 | HTML & SEO</li>
            <li>04 | more CSS</li>
            <li>05 | CSS & SSIs</li>
            <li>06 | Template development</li>
            <li>07 | Methodology</li>
            <li>08 | jQuery / Git</li>
          </ul>
          <h3>BLOG</h3>
          <ul>
            <li><a href="http://goteamtbd.tumblr.com/">News</a></li>
            <li><a href="http://goteamtbd.tumblr.com/tagged/resources">Resources</a></li>
            <li><a href="http://goteamtbd.tumblr.com/tagged/exercises">Exercises</a></li>
            <li><a href="http://goteamtbd.tumblr.com/tagged/code%20examples">Code Examples</a></li>
          </ul>
          <h3>CONTACT</h3>
          <ul>
            <li><a href="http://alistair.com">Alistair Caider</a></li>
          </ul>
          <h3>ASSOCIATED</h3>
          <ul>
            <li><a href="http://my.bcit.ca">my.bcit.ca</a></li>
            <li><a href="http://bcit.ca">bcit.ca</a></li>
            <li><a href="http://bcit.ca/cas/computing">bcit computing</a></li>
            <li><a href="/alumni.shtml">our Alumnis</a></li>
          </ul>
        </nav>