<section id="sub-navigation">
  <div class="row">
    <div class="columns large-12 right small-12">
      <div class="content-tabs right">
        <nav id="tabs">
          <ul>
            <li><a href="#lecture-notes"><span class="hidden">LECTURE </span>NOTES</a></li>
            <li><a href="#code-examples"><span class="hidden">CODE </span>EXAMPLES</a></li>
            <li><a href="#exercises">EXERCISES</a></li>
            <li><a href="#web-resources"><span class="hidden">WEB </span>RESOURCES</a></li>
          </ul>
        </nav>
      </div>
    </div>  
  </div>
</section>