<section id="sub-navigation">
  <div class="row">
    <div class="columns large-12 right">
      <div class="content-tabs right">
        <nav id="tabs">
          <ul>
            <li><a href="#lecture-notes">LECTURE NOTES</a></li>
            <li><a href="#code-examples">CODE EXAMPLES</a></li>
            <li><a href="#exercises">EXERCISES</a></li>
            <li><a href="#web-resources">WEB RESOURCES</a></li>
          </ul>
        </nav>
      </div>
    </div>  
  </div>
</section>