<header id="main">
  <div class="row">
    <div class="columns large-6">
      <a href="/client_site"><h1><b>TBD</b>- <b>T</b>otally <b>B</b>odacious <b>D</b>esigns</h1></a>
    </div>
    <div class="columns large-6 right">
      <nav id="main">
        <ul class="">
          <li><a href="about.shtml">About</a></li>
          <li><a href="rationale.shtml">Rationale</a></li>
          <li><a href="wireframes.shtml">Wireframes</a></li>
        </ul>
      </nav>
    </div>
    </div>
  </div>
</header>