<meta charset="UTF-8">
<link rel="stylesheet" href="assets/css/normalize.css">
<link rel="stylesheet" href="assets/css/foundation.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="assets/js/foundation.js"></script>
<script src="assets/js/foundation.orbit.js"></script>
<title>TBD :: Design for the masses~!</title>
