<header id="main">
  <div class="row">
    <div class="columns large-6">
      <a href="#"><h1><b>TBD</b>- Totally Bodacious <span style="color:#db3592;">Designs</span></h1></a>
    </div>
    <div class="columns large-6 right">
      <nav id="main">
        <ul class="">
          <li><a href="about.shtml">About</a></li>
          <li><a href="rationale.shtml">Rationale</a></li>
          <li><a href="documents.shtml">Documents</a></li>
          <li><a href="methodology.shtml">Our Methodology</a></li>
        </ul>
      </nav>
    </div>
    </div>
  </div>
</header>